language: ruby
script: ./build.sh
branches:
  only:
  - jekyll
rvm:
- 2.1.2
env:
  global:
    secure: mlq7fybiNMHmfghVQHF/z8Xc5qns2AHtY9a6TC/4H/bj4LylKi9nL5p3o+QcO0jWRj8HSI/N3vFIuEYngkgDcHLBXdK1KW4RNxnRNg7DxhRc36enn47pFbWeRtvtRWpVeskdXOfhzqCUlI9GhTa26q4uCYcBC0JnMe7VFbKUQxM=
