# Site settings
title: Mike Borozdin's Blog
email: mike.borozdin@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikeborozdin.com" # the base hostname & protocol for your site
twitter_username: mikeborozdin
github_username: mikeborozdin

# Build settings
markdown: kramdown

permalink: post/:title
paginate: 10
excerpt_separator: <!-- more -->

exclude: [vendor]